/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package rstudio.viewpilih;

import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.AbstractButton;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.KeyStroke;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import rstudio.config.Fungsi;
import rstudio.config.Koneksi;
import rstudio.config.TableColumnAdjuster;
import rstudio.model.Barang;
import rstudio.model.RincianPenj;
import rstudio.model.RincianPenj2TableModel;
import rstudio.model.RiwayatTransaksi;
import rstudio.model.RiwayatTransaksiTM;

/**
 *
 * @author DAFI
 */
public class RiwayatPengadaan extends javax.swing.JDialog {

    Connection con;
    RiwayatTransaksiTM tableRiwayat;
    RincianPenj2TableModel tableRincian;
    private Barang barang;
    private String sortBarang;
    Fungsi f;
    private String noFak="";
    //TableFilterHeader filterHeader;
    /**
     * Creates new form DataBarang
     */
    public RiwayatPengadaan(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        con = Koneksi.getKoneksi();
        tampilRiwayat();
        f.addEscapeListener(this);
        
        
        //filterHeader = new TableFilterHeader(jTableBarang, AutoChoices.DISABLED);
        
    }
    
    public static void oneKey(final AbstractButton button, String actionName, int key) {
        button.getInputMap(JButton.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(key, 0), actionName);

        button.getActionMap().put(actionName, new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                button.doClick();
            }
        });
    }

    
    public Barang getRiwayat(){
         setVisible(true);
         return barang;
    }
    
    public JTable getjTableRiwayat() {
        return jTableRiwayat;
    }
    
    public RiwayatTransaksiTM getMode(){
        return tableRiwayat;
    }
    
    public void tampilRiwayat(){
        tableRiwayat = new RiwayatTransaksiTM();
        int no =1;
        try{
            String tampil="SELECT * FROM tb_pembelian WHERE status='0'";
            Statement stat=con.createStatement();
            ResultSet set=stat.executeQuery(tampil);
            while (set.next()){
                RiwayatTransaksi b = new RiwayatTransaksi();
                
                SimpleDateFormat sourceDateFormat = new SimpleDateFormat("yyyy-MM-dd");
                SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
                Date dTgl = sourceDateFormat.parse(set.getString("tgl_nota"));
                String tgl = sdf.format(dTgl);
                
                b.setNo(String.valueOf(no));
                b.setNoFaktur(set.getString("no_faktur"));
                b.setTgl(tgl);
                b.setPetugas(set.getString("user"));
                
                tableRiwayat.add(b);
                no++;
            }
            jTableRiwayat.setModel(tableRiwayat);
            
            jTableRiwayat.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
            TableColumnAdjuster tca = new TableColumnAdjuster(jTableRiwayat);
            tca.adjustColumns();
            
            
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Data tidak bisa ditampilkan: "+e.getMessage());
        } catch (ParseException ex) {
            Logger.getLogger(RiwayatPengadaan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRiwayat = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pengadaan Belum Selesai");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Riwayat Pengadaan"));

        jTableRiwayat.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jTableRiwayat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableRiwayat.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                jTableRiwayatAncestorMoved(evt);
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jTableRiwayat.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTableRiwayatFocusGained(evt);
            }
        });
        jTableRiwayat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableRiwayatMouseClicked(evt);
            }
        });
        jTableRiwayat.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTableRiwayatPropertyChange(evt);
            }
        });
        jTableRiwayat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTableRiwayatKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTableRiwayat);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableRiwayatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableRiwayatKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTableRiwayatKeyPressed

    private void jTableRiwayatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableRiwayatMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jTableRiwayatMouseClicked

    private void jTableRiwayatFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTableRiwayatFocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_jTableRiwayatFocusGained

    private void jTableRiwayatAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTableRiwayatAncestorMoved
        // TODO add your handling code here:
     
    }//GEN-LAST:event_jTableRiwayatAncestorMoved

    private void jTableRiwayatPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTableRiwayatPropertyChange
        // TODO add your handling code here:

    }//GEN-LAST:event_jTableRiwayatPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RiwayatPengadaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RiwayatPengadaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RiwayatPengadaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RiwayatPengadaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RiwayatPengadaan dialog = new RiwayatPengadaan(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableRiwayat;
    // End of variables declaration//GEN-END:variables
}
